# cloudbuild.yaml

steps:
  # 1) Build the image using your Dockerfile
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE_NAME}", "."]

  # 2) Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE_NAME}"]

  # 3) Deploy the image to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_IMAGE_NAME}",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated"
      ]

# 👇 NEW: these are *top-level* fields, NOT a step
logsBucket: "gs://phoenix-elite-build-logs"
options:
  logging: GCS_ONLY

substitutions:
  _SERVICE_NAME: phoenix-backend
  _REGION: us-west1
  _IMAGE_NAME: us-west1-docker.pkg.dev/second-folio-468704-a5/phoenix-backend/phoenix-backend:latest

images:
  - "${_IMAGE_NAME}"
